package config

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
)

// =============================================================================
// Schema & Introspection Engine
// =============================================================================

// FieldSpec represents declared metadata extracted from configuration struct tags.
type FieldSpec struct {
	EnvKey       string `json:"env_key"`
	DefaultValue string `json:"default_value"`
	Description  string `json:"description"`
}

// SchemaEngine inspects configuration structures and generates documentation templates.
type SchemaEngine struct{}

// NewSchemaEngine instantiates a schema and introspection engine.
func NewSchemaEngine() *SchemaEngine {
	return &SchemaEngine{}
}

// ExtractSpecs recursively traverses struct fields to discover declared environment configurations.
func (s *SchemaEngine) ExtractSpecs(v interface{}) []FieldSpec {
	val := reflect.ValueOf(v)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	var specs []FieldSpec
	s.extractFromType(val.Type(), &specs)
	return specs
}

func (s *SchemaEngine) extractFromType(t reflect.Type, specs *[]FieldSpec) {
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)

		// Recurse into nested struct sections (except custom leaf types like Duration)
		if field.Type.Kind() == reflect.Struct && field.Type.Name() != "Duration" {
			s.extractFromType(field.Type, specs)
			continue
		}

		envKey := field.Tag.Get("env")
		if envKey == "" {
			continue
		}

		*specs = append(*specs, FieldSpec{
			EnvKey:       envKey,
			DefaultValue: field.Tag.Get("default"),
			Description:  field.Tag.Get("desc"),
		})
	}
}

// GenerateEnvTemplate produces a clean, self-documenting .env.example string with descriptions and defaults.
func (s *SchemaEngine) GenerateEnvTemplate(specs []FieldSpec) string {
	var sb strings.Builder
	sb.WriteString("# ==============================================================================\n")
	sb.WriteString("# Automated Environment Configuration Template (.env.example)\n")
	sb.WriteString("# Generated by config.SchemaEngine\n")
	sb.WriteString("# ==============================================================================\n\n")

	for _, spec := range specs {
		if spec.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", spec.Description))
		}
		if spec.DefaultValue != "" {
			sb.WriteString(fmt.Sprintf("# Default: %s\n", spec.DefaultValue))
		}
		sb.WriteString(fmt.Sprintf("%s=%s\n\n", spec.EnvKey, spec.DefaultValue))
	}

	return sb.String()
}

// WriteEnvExample creates an .env.example file on disk based on the configuration struct tags.
func (s *SchemaEngine) WriteEnvExample(outputPath string, cfg *Configuration) error {
	if cfg == nil {
		cfg = DefaultConfiguration()
	}

	specs := s.ExtractSpecs(cfg)
	content := s.GenerateEnvTemplate(specs)

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create directory for env template %s: %w", dir, err)
	}

	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write env example to %s: %w", outputPath, err)
	}

	return nil
}
